### PR TITLE
Versioneye Integration

### PR DESCRIPTION
**Pull request by stefan-kolb**
Hi @reiz 

I got something working here. There are still some points we need to discuss.
- [ ] How does your integration inside the whole architecture of versioneye work. Currently, I've just duplicated the `mongoid.yml` and the `settings.json` and included `require 'versioneye-core'` inside the crawler. However, normally the crawler would just need knowledge about the MongoDB database and nothing else.
- [x] How should the scheduler integration work. I've seen you used systemd in one crawler. Actually, I had a few problems with rufus-scheduler over the last years (memory leaks, ...) I'd rather look for an approach where a scheduler tasks just runs `docker run` oculus at certain intervals. The container is removed afterwards and takes no more memory etc.
- [ ] How does your monitoring work, e.g., how do we recognize that our crawler isn't working anymore.
- [x] What's the best way to integrate the runtime languages. At the moment I populate the last version attribute inside the `Language` model. And we talked about adding each runtime as `Product` under `C` for simplicity right now. If the functionality/data should be really usable this has to be made more visible to the end users.
- [x] I'm also not sure what every attribute inside `Product` is used for. I can probably poulate a lot of these attributes if I know what they are intended for.
- [ ] Do I need to manually send out notifications after adding new versions?

Demo output:

``` sh
Processing complete crawl...
clojure: Version 1.8.0
cobol: Version 2014
dart: Version 1.5.2
dotnet: Version 4.5.2
erlang: Version 19.0.2
go: Version 1.6.3
groovy: Version 2.4.7
java: Version 1.8.0_92
lua: Version 5.3.3
node: Version 5.11.1
perl: Version 5.24.0
php: Version 7.0.8
python: Version 3.5.2
ruby: Version 2.3.1
scala: Version 2.11.8
Finished complete crawl!
Processing time was 25.797606.
```

Cheers, Stefan

### CODE REVIEW

**Comment by reiz** [comment]
Hey @stefan-kolb. I just send you 2 of my Ruby crawlers via email as an example how to use the versioneye-core project in the crawlers to access the database and to write notifications. 

As this project is currently completely separated from the other crawling projects you don't have to use Rufus. If the crawling process is started inside a Dockerfile with the CMD command, that's just fine for me. 

The monitoring at VersionEye is currently a moving part. That's something we have to improve. 

I was just thinking about the namespaces and thought it's not very intuitive to put them under the `C` namespace even if the runtimes are implemented in C. We track the PHP runtime already and I  realised that it is already under the `php/php` namesapce. See here: https://www.versioneye.com/php/php/7.0.8. I think it makes sense to put the runtime under the corresponding language namespace. For example `ruby/ruby` or `dart/dart`. What do you think? 

For the product model it should be fine if you fill out only this ones: 

```
  field :name, type: String
  field :name_downcase, type: String
  field :prod_key     , type: String # Unique identifier inside a language
  field :prod_key_dc  , type: String # prod_key downcased .. important for NPM
  field :prod_type    , type: String # Identifies the package manager
  field :language     , type: String
  field :version      , type: String, default: '0.0.0+NA' # latest stable version
  field :description       , type: String
```

For example for Ruby: 

```
:name => 'Ruby',
:name_downcase => 'ruby',
:prod_key => 'ruby',
:prod_key_dc => 'ruby',
:prod_type => nil
:language => 'Ruby',
:version => '2.3.1',
:description => 'The Ruby MRI runtime.'
```

The `product.version` always contains the newest version. A list of ALL versions is in `product.versions` as an embedded document. 

Let me know if you have further questions. I'm happy to help.

**Comment by stefan-kolb** [comment]
If we cannot reasonably make them accessible via /language I guess /language/language (e.g. ruby/ruby) is the best place right now.

**Comment by reiz** [comment]
@stefan-kolb we can make them available under `/language` as well. But if we want to display a product page for it must have this structure `language/prod_key`. Then it will be indexed by ElasticSearch, show up in search results and people can "follow" it and get notifications for new versions.

**Comment by stefan-kolb** [comment]
@reiz Ok, I implemented this stuff. Maybe you can take a look. We might also do a code review together to sort out the last problems and integrate it into Versioneye.

**Comment by stefan-kolb** [comment]
@reiz WDYT?

**Comment by stefan-kolb** [comment]
@reiz Was ist jetzt Sache hier? Hast du doch kein Interesse? Warte seit Monaten auf Rückmeldung. Wenn es für dich nicht interessant ist ist es zwar schade um die Arbeit aber dann closen wir es eben.

**Pull request closed without merging**
